<?php

// @codingStandardsIgnoreFile

/* @var $block \GoMage\Feed\Block\Adminhtml\Feed\Edit\Tab\Content\Mapping */
?>
<?php
    $element        = $block->getElement();
    $_htmlId        = $element->getHtmlId();
    $_htmlClass     = $element->getClass();
    $_htmlName      = $element->getName();
    $_types         = $block->getType();
    $_extendedTypes = $block->getExtendedType();
    $_outputs       = $block->getOutput();
    $_attributes    = $block->getProductAttributes();
?>

<style type="text/css">
@-moz-document url-prefix() { /* Only target Gecko. (Breaks layout in IE.) */
  .admin__scope-old .fieldset-wrapper, .admin__scope-old .fieldset { display: table-cell; }
}
.mapping_table select,
.filter_table select,
.mapping_table .input-text,
.filter_table .input-text{
  max-width: 150px;
}
</style>

<div class="fm-block">
  <div class="fm-block-title">
    <div class="draggable-handle" title="Sort"></div>
    <div class="fm-block-title-right">
      <button class="action-default"><span>Delete</span></button>
      <button class="action-default"><span>Edit</span></button>
    </div>    
    <div class="fm-block-title-left">
      <div class="fm-block-title-text">Lorem Ipsum Dolor Sit Amet</div>
      <div class="fm-block-title-sub">
        <div class="fm-block-title-sub-item"><strong>Type:</strong> Static Value</div>
        <div class="fm-block-title-sub-item"><strong>Value:</strong> Active From</div>
        <div class="fm-block-title-sub-sep"></div>
        <div class="fm-block-title-sub-item"><strong>Prefix Type:</strong> Attribute</div>
        <div class="fm-block-title-sub-item"><strong>Prefix Value</strong>: Active Form</div>
        <div class="fm-block-title-sub-sep"></div>
        <div class="fm-block-title-sub-item"><strong>Suffix Type:</strong> Suffix Type long text here</div>
      </div>
    </div>
  </div>
  <div class="fm-block-content">
    Content here
  </div>
</div>

<div class="fm-block">
  <div class="fm-block-title">
    <div class="draggable-handle" title="Sort"></div>
    <div class="fm-block-title-right">
      <button class="action-default"><span>Delete</span></button>
      <button class="action-default"><span>Edit</span></button>
    </div>    
    <div class="fm-block-title-left">
      <div class="fm-block-title-text">Lorem Ipsum</div>
      <div class="fm-block-title-sub">
        <div class="fm-block-title-sub-item"><strong>Type:</strong> Static Value</div>
        <div class="fm-block-title-sub-item"><strong>Value:</strong> Active From</div>
      </div>
    </div>
  </div>
  <div class="fm-block-content">
    Content here
  </div>
</div>

<div class="fm-block __opened">
  <div class="fm-block-title">
    <div class="draggable-handle" title="Sort"></div>
    <div class="fm-block-title-right">
      <button class="action-default"><span>Delete</span></button>
      <button class="action-default primary"><span>Save</span></button>
    </div>    
    <div class="fm-block-title-left">
      <div class="fm-block-title-text">Lorem Ipsum Dolor Sit Amet</div>
      <div class="fm-block-title-sub">
        <div class="fm-block-title-sub-item"><strong>Type:</strong> Static Value</div>
        <div class="fm-block-title-sub-item"><strong>Value:</strong> Active From</div>
        <div class="fm-block-title-sub-sep"></div>
        <div class="fm-block-title-sub-item"><strong>Prefix Type:</strong> Attribute</div>
        <div class="fm-block-title-sub-item"><strong>Prefix Value</strong>: Active Form</div>
        <div class="fm-block-title-sub-sep"></div>
        <div class="fm-block-title-sub-item"><strong>Suffix Type:</strong> Suffix Type long text here</div>
      </div>
    </div>
  </div>
  <div class="fm-block-content">
    
    <fieldset class="admin__fieldset fm-block-content-line">
   
      <div class="admin__field required _required">
        <label class="admin__field-label"><span>Field Name</span></label>
        <div class="admin__field-control">
          <input type="text" class="admin__control-text" />
        </div>
      </div>
      
      <div class="admin__field required _required">
        <label class="admin__field-label"><span>Type</span></label>
        <div class="admin__field-control">
          <select>
            <option>Attribute</option>
            <option>Attribute 2</option>
          </select>
        </div>
      </div>
      
      <div class="admin__field required _required">
        <label class="admin__field-label"><span>Value</span></label>
        <div class="admin__field-control">
          <select>
            <option>Attribute</option>
            <option>Attribute 2</option>
          </select>
        </div>
      </div>
      
    </fieldset>
    
    <fieldset class="admin__fieldset fm-block-content-line">
      <div class="admin__field">
        <label class="admin__field-label"><span>Output Types</span></label>
        <div class="admin__field-control">
          <select class="admin__control-multiselect" multiple="multiple">
            <option>Default</option>
            <option>Integer</option>
            <option>Float</option>
            <option>Strip Tags</option>
            <option>Encode Special Chars</option>
            <option>Decode Special Chars</option>
            <option>Delete Space</option>
            <option>Big to Small</option>
          </select>
        </div>
      </div>
      <div class="admin__field">
        <label class="admin__field-label"><span>Symbols Limit</span></label>
        <div class="admin__field-control">
          <input type="text" class="admin__control-text" />
        </div>
      </div>
    </fieldset>
    
    <fieldset class="admin__fieldset fm-block-content-line">
      <div class="admin__field">
        <label class="admin__field-label"><span>Prefix</span></label>
        <div class="admin__field-control">
          <div class="admin__actions-switch" data-role="switcher">
              <input class="admin__actions-switch-checkbox" type="checkbox" checked="checked" />
              <label class="admin__actions-switch-label">
                  <span class="admin__actions-switch-text">On</span>
              </label>
          </div>
        </div>
      </div>
      
      <div class="admin__field">
        <label class="admin__field-label"><span>Prefix Type</span></label>
        <div class="admin__field-control">
          <select>
            <option>Attribute</option>
            <option>Attribute 2</option>
          </select>
        </div>
      </div>
      
      <div class="admin__field">
        <label class="admin__field-label"><span>Prefix Value</span></label>
        <div class="admin__field-control">
          <select>
            <option>Attribute</option>
            <option>Attribute 2</option>
          </select>
        </div>
      </div>
      
    </fieldset>
    
    <fieldset class="admin__fieldset fm-block-content-line">
      <div class="admin__field">
        <label class="admin__field-label"><span>Suffix</span></label>
        <div class="admin__field-control">
          <div class="admin__actions-switch" data-role="switcher">
              <input class="admin__actions-switch-checkbox" type="checkbox" />
              <label class="admin__actions-switch-label">
                  <span class="admin__actions-switch-text">Off</span>
              </label>
          </div>
        </div>
      </div>
    </fieldset>
  </div>
</div>

<div class="fm-actions">
  <button class="action-default"><span>Add New Row</span></button>
</div>


<div class="field">
    <div class="control" style="float:none;width:100%;overflow:auto;">
        <table class="admin__control-table mapping_table" id="mapping_table">
            <thead>
                <tr>
                    <th class="col-draggable col-order"></th>
                    <th class="col-name required"><?php echo __('Field Name') ?></th>
                    <th class="col-type"><?php echo __('Prefix Type') ?></th>
                    <th class="col-value"><?php echo __('Prefix Value') ?></th>
                    <th class="col-type"><?php echo __('Type') ?></th>
                    <th class="col-value"><?php echo __('Value') ?></th>
                    <th class="col-type"><?php echo __('Suffix Type') ?></th>
                    <th class="col-value"><?php echo __('Suffix Value') ?></th>
                    <th class="col-output"><?php echo __('Output Type') ?></th>
                    <th class="col-limit"><?php echo __('Symbols Limit') ?></th>
                    <th class="col-delete"><?php echo __('Action') ?></th>
                </tr>
            </thead>
            <tbody data-role="<?php echo $_htmlId ?>_container" id="<?php echo $_htmlId ?>_container"></tbody>
            <tfoot>
                <tr>
                    <td colspan="11" class="col-actions-add"><?php echo $block->getAddButtonHtml() ?></td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
<script id="mapping-row-template" type="text/x-magento-template">
    <tr>
        <td class="col-draggable col-order">
            <div data-role="draggable-handle" class="draggable-handle" title="<?php echo __('Sort'); ?>"></div>
            <input data-role="order" type="hidden" name="<?php echo $_htmlName ?>[<%- data.index %>][order]" value="<%- data.order %>" id="mapping_row_<%- data.index %>_order" />
        </td>
        <td class="col-name">
            <input class="input-text <?php echo $_htmlClass ?> required-entry" type="text" name="<?php echo $_htmlName ?>[<%- data.index %>][name]" value="<%- data.name %>" id="mapping_row_<%- data.index %>_name" />
        </td>
        <td class="col-type">
            <select class="select admin__control-select" name="<?php echo $_htmlName ?>[<%- data.index %>][prefix_type]"
                    id="mapping_row_<%- data.index %>_prefix_type"
                    onchange="mappingControl.changeType(this);"
                    data-value-select="mapping_row_<%- data.index %>_prefix_value_select"
                    data-value-input="mapping_row_<%- data.index %>_prefix_value_input">
                <?php foreach ($_types as $_type): ?>
                    <option value="<?php echo $_type['value'] ?>" <% if (typeof data.prefix_type != 'undefined' && data.prefix_type == <?php echo $_type['value'] ?>) { %> selected="selected" <% } %>><?php echo $_type['label'] ?></option>
                <?php endforeach ?>
            </select>
        </td>
        <td class="col-value">
            <select class="select admin__control-select" name="<?php echo $_htmlName ?>[<%- data.index %>][prefix_value]"
                    id="mapping_row_<%- data.index %>_prefix_value_select"
                    <% if (data.prefix_type == '2') { %> disabled="disabled" style="display:none" <% } %>>
                <option value=""><?php echo __('Not Set') ?></option>
                <?php foreach ($_attributes as $_attribute): ?>
                    <option value="<?php echo $_attribute['value'] ?>" <% if (typeof data.prefix_value != 'undefined' && data.prefix_value == '<?php echo $_attribute['value'] ?>') { %> selected="selected" <% } %>><?php echo $_attribute['label'] ?></option>
                <?php endforeach ?>
            </select>
            <input type="text" class="input-text <?php echo $_htmlClass ?>"
                   name="<?php echo $_htmlName ?>[<%- data.index %>][prefix_value]"
                   id="mapping_row_<%- data.index %>_prefix_value_input"
                    <% if (data.prefix_type != '2') { %> disabled="disabled" style="display:none" <% } %>
                    value="<%- data.prefix_value %>" />
        </td>
        <td class="col-type">
            <select class="select admin__control-select" name="<?php echo $_htmlName ?>[<%- data.index %>][type]"
                    id="mapping_row_<%- data.index %>_type"
                    onchange="mappingControl.changeType(this);"
                    data-value-select="mapping_row_<%- data.index %>_value_select"
                    data-value-input="mapping_row_<%- data.index %>_value_input">
                <?php foreach ($_extendedTypes as $_type): ?>
                    <option value="<?php echo $_type['value'] ?>" <% if (typeof data.type != 'undefined' && data.type == <?php echo $_type['value'] ?>) { %> selected="selected" <% } %>><?php echo $_type['label'] ?></option>
                <?php endforeach ?>
            </select>
        </td>
        <td class="col-value">
            <select class="select admin__control-select" name="<?php echo $_htmlName ?>[<%- data.index %>][value]"
                    id="mapping_row_<%- data.index %>_value_select"
                    <% if (data.type == '2') { %> disabled="disabled" style="display:none" <% } %>>
                <option value=""><?php echo __('Not Set') ?></option>
                <?php foreach ($_attributes as $_attribute): ?>
                    <option value="<?php echo $_attribute['value'] ?>" <% if (typeof data.value != 'undefined' && data.value == '<?php echo $_attribute['value'] ?>') { %> selected="selected" <% } %>><?php echo $_attribute['label'] ?></option>
                <?php endforeach ?>
            </select>
            <input type="text" class="input-text <?php echo $_htmlClass ?>"
                   name="<?php echo $_htmlName ?>[<%- data.index %>][value]"
                   id="mapping_row_<%- data.index %>_value_input"
                    <% if (data.type != '2') { %> disabled="disabled" style="display:none" <% } %>
                    value="<%- data.value %>" />
        </td>
        <td class="col-type">
            <select class="select admin__control-select" name="<?php echo $_htmlName ?>[<%- data.index %>][suffix_type]"
                    id="mapping_row_<%- data.index %>_suffix_type"
                    onchange="mappingControl.changeType(this);"
                    data-value-select="mapping_row_<%- data.index %>_suffix_value_select"
                    data-value-input="mapping_row_<%- data.index %>_suffix_value_input">
                <?php foreach ($_types as $_type): ?>
                    <option value="<?php echo $_type['value'] ?>" <% if (typeof data.suffix_type != 'undefined' && data.suffix_type == <?php echo $_type['value'] ?>) { %> selected="selected" <% } %>><?php echo $_type['label'] ?></option>
                <?php endforeach ?>
            </select>
        </td>
        <td class="col-value">
            <select class="select admin__control-select" name="<?php echo $_htmlName ?>[<%- data.index %>][suffix_value]"
                    id="mapping_row_<%- data.index %>_suffix_value_select"
                    <% if (data.suffix_type == '2') { %> disabled="disabled" style="display:none" <% } %>>
                <option value=""><?php echo __('Not Set') ?></option>
                <?php foreach ($_attributes as $_attribute): ?>
                    <option value="<?php echo $_attribute['value'] ?>" <% if (typeof data.suffix_value != 'undefined' && data.suffix_value == '<?php echo $_attribute['value'] ?>') { %> selected="selected" <% } %>><?php echo $_attribute['label'] ?></option>
                <?php endforeach ?>
            </select>
            <input type="text" class="input-text <?php echo $_htmlClass ?>"
                   name="<?php echo $_htmlName ?>[<%- data.index %>][suffix_value]"
                   id="mapping_row_<%- data.index %>_prefix_value_input"
                    <% if (data.suffix_value != '2') { %> disabled="disabled" style="display:none" <% } %>
                    value="<%- data.suffix_value %>" />
        </td>
        <td class="col-output">
            <select class="select admin__control-select" name="<?php echo $_htmlName ?>[<%- data.index %>][output]" id="mapping_row_<%- data.index %>_output">
                <?php foreach ($_outputs as $_output): ?>
                    <option value="<?php echo $_output['value'] ?>" <% if (typeof data.output != 'undefined' && data.output == <?php echo $_output['value'] ?>) { %> selected="selected" <% } %>><?php echo $_output['label'] ?></option>
                <?php endforeach ?>
            </select>
        </td>
        <td class="col-limit">
            <input class="input-text <?php echo $_htmlClass ?> validate-number" type="text" name="<?php echo $_htmlName ?>[<%- data.index %>][limit]" value="<%- data.limit %>" id="mapping_row_<%- data.index %>_limit" />
        </td>
        <td class="col-delete">
            <button title="<?php echo __("Delete") ?>" type="button" class="action- scalable delete icon-btn" id="mapping_row_<%- data.index %>_delete_button" onclick="return mappingControl.deleteItem(event);">
                <span><?php echo __("Delete") ?></span>
            </button>
        </td>
        </tr>
</script>
<script>
//<![CDATA[

require([
    'jquery',
    'mage/template',
    'jquery/ui',
    'prototype'
], function (jQuery, mageTemplate) {

var mappingControl = {
    template: mageTemplate('#mapping-row-template'),
    itemsCount: 0,
    addItem : function (data) {
        if (typeof(data) == 'undefined'){
            data = {};
        }
        data.order = this.itemsCount;
        data.index = this.itemsCount;


        Element.insert($('<?php echo $_htmlId ?>_container'), {
            bottom : this.template({
                data: data
            })
        });

        $('<?php echo $_htmlId ?>_container').select('input', 'select').each(function(el){
            if (el.hasOwnProperty('setHasChanges')) {
                Event.observe(el, 'change', el.setHasChanges.bind(el));
            }
        });

        this.itemsCount++;
    },
    deleteItem: function(event) {
        var tr = Event.findElement(event, 'tr');
        if (tr) {
            Element.remove(tr);
        }
        return false;
    },
    changeType: function (control){

        control = jQuery(control);
        var value_select = jQuery('#' + control.attr('data-value-select'));
        var value_input = jQuery('#' + control.attr('data-value-input'));

        if (control.val() == '2'){
            value_select.hide();
            value_select.prop( "disabled", true);
            value_input.show();
            value_input.prop( "disabled", false);
        }else{
            value_input.hide();
            value_input.prop( "disabled", true);
            value_select.show();
            value_select.prop( "disabled", false);
        }
    }
};
<?php foreach ($block->getValues() as $_item): ?>
    mappingControl.addItem(<?php echo $_item->toJson() ?>);
<?php endforeach; ?>

jQuery(function($) {
    $('[data-role=<?php echo $_htmlId ?>_container]').sortable({
        distance: 8,
        tolerance: "pointer",
        axis: 'y',
        update: function() {
            $('[data-role=<?php echo $_htmlId ?>_container] [data-role=order]').each(function(index, element) {
                $(element).val(index + 1);
            });
        }
    });
});

window.mappingControl = mappingControl;
//]]>

});
</script>
